export const categories = [
  {
    id: 0,
    name: "All",
    imageLink: require("../assets/images/All.png"),
    jokeCount: 10000,
  },
  {
    id: 1,
    name: "Animal",
    imageLink: require("../assets/images/Animal.png"),
    jokeCount: 656,
  },
  {
    id: 2,
    name: "Other / Misc",
    imageLink: require("../assets/images/Other___Misc.png"),
    jokeCount: 2305,
  },
  {
    id: 3,
    name: "Bar",
    imageLink: require("../assets/images/Bar.png"),
    jokeCount: 154,
  },
  {
    id: 4,
    name: "One Liners",
    imageLink: require("../assets/images/One_Liners.png"),
    jokeCount: 917,
  },
  {
    id: 5,
    name: "Puns",
    imageLink: require("../assets/images/Puns.png"),
    jokeCount: 457,
  },
  {
    id: 6,
    name: "Lawyer",
    imageLink: require("../assets/images/Lawyer.png"),
    jokeCount: 157,
  },
  {
    id: 7,
    name: "Sports",
    imageLink: require("../assets/images/Sports.png"),
    jokeCount: 134,
  },
  {
    id: 8,
    name: "Medical",
    imageLink: require("../assets/images/Medical.png"),
    jokeCount: 208,
  },
  {
    id: 9,
    name: "News / Politics",
    imageLink: require("../assets/images/News___Politics.png"),
    jokeCount: 279,
  },
  {
    id: 10,
    name: "Men / Women",
    imageLink: require("../assets/images/Men___Women.png"),
    jokeCount: 925,
  },
  {
    id: 11,
    name: "Gross",
    imageLink: require("../assets/images/Gross.png"),
    jokeCount: 254,
  },
  {
    id: 12,
    name: "Blond",
    imageLink: require("../assets/images/Blond.png"),
    jokeCount: 598,
  },
  {
    id: 13,
    name: "Yo Momma",
    imageLink: require("../assets/images/Yo_Momma.png"),
    jokeCount: 600,
  },
  {
    id: 14,
    name: "Redneck",
    imageLink: require("../assets/images/Redneck.png"),
    jokeCount: 241,
  },
  {
    id: 15,
    name: "Religious",
    imageLink: require("../assets/images/Religious.png"),
    jokeCount: 402,
  },
  {
    id: 16,
    name: "At Work",
    imageLink: require("../assets/images/At_Work.png"),
    jokeCount: 288,
  },
  {
    id: 17,
    name: "College",
    imageLink: require("../assets/images/College.png"),
    jokeCount: 131,
  },
  {
    id: 18,
    name: "Lightbulb",
    imageLink: require("../assets/images/Lightbulb.png"),
    jokeCount: 110,
  },
  {
    id: 19,
    name: "Children",
    imageLink: require("../assets/images/Children.png"),
    jokeCount: 605,
  },
  {
    id: 20,
    name: "Insults",
    imageLink: require("../assets/images/Insults.png"),
    jokeCount: 276,
  },
  {
    id: 21,
    name: "Knock-Knock",
    imageLink: require("../assets/images/Knock_Knock.png"),
    jokeCount: 167,
  },
  {
    id: 22,
    name: "Tech",
    imageLink: require("../assets/images/Tech.png"),
    jokeCount: 151,
  },
  {
    id: 23,
    name: "Blonde",
    imageLink: require("../assets/images/Blonde.png"),
    jokeCount: 1,
  },
  {
    id: 24,
    name: "Yo Mama",
    imageLink: require("../assets/images/Yo_Mama.png"),
    jokeCount: 3,
  },
];
